color0 #141219
color1 #ffb4ab
color2 #ccbdff
color3 #cbc0ee
color4 #ffaede
color5 #ccbdff
color6 #cbc0ee
color7 #e6e0ea
color8 #938e9d
color9 #ffb4ab
color10 #ccbdff
color11 #cbc0ee
color12 #ffaede
color13 #ccbdff
color14 #cbc0ee
color15 #e6e0ea

cursor                #e6e0ea
cursor_text_color     #141219
background            #141219
foreground            #e6e0ea
selection_foreground  #cac4d3
selection_background  #484552
active_border_color   #ccbdff
inactive_border_color #484552
url_color             #ccbdff

active_tab_foreground   #351a7e
active_tab_background   #ccbdff
inactive_tab_foreground #cac4d3
inactive_tab_background #484552
cursor_trail_color      #cac4d3
