# Window rules (see docs/user/window-rules.md) ---------------------------

# Blur all windows
[[window_rule]]
blur = true
blur_optimized = true

[[window_rule]]
match.app_id = "^dev.noctalia.Noctalia$"
default_floating = true
default_size = [1020, 900]
blur_popups = false

[[window_rule]]
match.app_id = "^dev.noctalia.UmbrielSharePicker$"
default_floating = true
default_size = [800, 600]

# Browsers do not expose a semantic PiP role or control global window position.
[[window_rule]]
match.title = "^(Picture-in-Picture|Picture in picture)$"
default_floating = true
default_maximize = false
default_pinned = true
# default_position = { x = 20, y = 20, anchor = "bottom_right" }

# [[window_rule]]
# match.is_focused = false
# opacity = 0.85

[[window_rule]]
match.app_id = "^(neovide|cursor|com.anthropic.Claude|kitty|code)$"
default_workspace = 1

[[window_rule]]
match.app_id = "^(zen|firefox|brave-browser)$"
default_workspace = 2

[[window_rule]]
match.app_id = "^(Minecraft|org.vinegarhq.Sober)$"
default_workspace = 3

[[window_rule]]
match.app_id = "^(vesktop|com.obsproject.Studio)$"
default_workspace = 4

[[window_rule]]
match.app_id = "^(net.nokyan.Resources)$"
default_floating = true

[[window_rule]]
match.app_id = "^(steam_proton|steam_app.*|overwatch|overwatch\\.exe)$"
default_floating = true
default_workspace = 3

# Float common dialogs by title
[[window_rule]]
match.title = "^(Open File|Select|Choose a wallpaper|Open Folder|Save As|Library|Choose Where to Download|File Operation Progress|Rename|Copy Files|Move Files|Search Files)"

default_floating = true
[[window_rule]]
match.app_id = "^(spotify)$"
default_width = 0.667

# Steam notification toasts
[[window_rule]]
match.title = "^notificationtoasts_.+_desktop"
default_position = { x = 0, y = 0, anchor = "bottom_right" }
default_focused = false
default_pinned = true

# Layer rules (see docs/user/layer-rules.md) ---------------------------

[[layer_rule]]
match.namespace="^noctalia-(bar-[^\"]+|notification|dock|panel|attached-panel|osd)$"
blur = true
blur_ignore_alpha = 0.5
blur_optimized = false

# Security context rules (see docs/user/security.md) ----------------------

# Grant a sandboxed clipboard manager the data-control protocol
# [[security_context_rule]]
# match.sandbox_engine = 'org\.flatpak'
# match.app_id = 'org\.example\.ClipboardManager'
# allow_globals = ["ext_data_control_manager_v1"]
